# Example dbt_project.yml file
name: 'card_game'

#profile: card_game

dbt-cloud:
    project-id: 70471823443890


models: 

    card_game:

        #by default will use the schema  dbt_cmsika

        livestream_views_events:
            +materialized: view

        card_round_duration_game: 
            +materialized: view


    

    
